version: '2'
services:
  alive-checker:
    restart: always
    build: alive-checker
    ports:
      - 3000:3000
    links:
      - geth:node
    depends_on:
      - geth
  geth:
    build: node
    ports:
      - 8544:8544
      - 30303:30303
  nginx:
    image: "nginx"
    links:
      - geth:node
      - alive-checker:checker
    ports:
      - 8545:8545
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf