version: '2'
services:
  alive-checker:
    restart: always
    build: alive-checker
    ports:
      - 3000:3000
    links:
      - geth:node
    depends_on:
      - geth
  geth:
    build: node
    ports:
      - 8544:8544
      - 30303:30303
  nginx:
    image: "nginx"
    restart: always
    links:
      - geth:node
      - alive-checker:checker
    ports:
      - 8545:8545
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  reporter:
    image: "ethereumex/eth-net-intelligence-api"
    restart: always
    links:
      - geth:node
    depends_on:
      - geth
    environment:
      - NODE_ENV=production
      - RPC_HOST=node
      - RPC_PORT=8544
      - LISTENING_PORT=30303
      - INSTANCE_NAME=${NAME}
      - WS_SERVER=${WS_SERVER}
      - WS_SECRET=${WS_SECRET}
      - VERBOSITY=2
      
